# Generated by Django 3.1.4 on 2021-01-18 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmbody', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('pmreciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmreciever', to=settings.AUTH_USER_MODEL)),
                ('pmsender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmsender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
